drop table if exists ratpbot.TRAFFIC;
drop table if exists ratpbot.TRAFFIC_SUBSCRIPTION;
drop table if exists ratpbot.DAYALERT;
drop table if exists ratpbot.ALERT;
drop table if exists ratpbot.ALERTFORM;
drop table if exists ratpbot.ALERTDAYFORM;
drop table if exists ratpbot.WELCOMEALERTHOUR;

CREATE TABLE ratpbot.TRAFFIC (
  "LINE" VARCHAR(255) PRIMARY KEY,
  "TRANSPORT" VARCHAR(255),
  "SLUG" VARCHAR(255),
  "TITLE" VARCHAR(255),
  "MESSAGE" VARCHAR(255)
);

CREATE TABLE ratpbot.TRAFFIC_SUBSCRIPTION (
  "LINE" VARCHAR(255),
  "TRANSPORT" VARCHAR(255),
  "USERID" VARCHAR(255),

  PRIMARY KEY ("LINE", "USERID", "TRANSPORT")
);

CREATE TABLE ratpbot.ALERT (
  "ID" serial PRIMARY KEY,
  "USERID" VARCHAR(255),
  "TRAINTYPE" VARCHAR(255),
  "TRAINCODE" VARCHAR(255),
  "STATION" VARCHAR(255),
  "HOUR" INTEGER,
  "MINUTES" INTEGER,
  "DAY" INTEGER,
  "MONTH" INTEGER,
  "YEAR" INTEGER,

  CONSTRAINT UNIQ_ALERT_VALUES UNIQUE ("USERID", "TRAINTYPE", "TRAINCODE", "STATION", "HOUR", "MINUTES"),
  CONSTRAINT CHECK_HOUR CHECK("HOUR" >= 0 AND "HOUR" < 24),
  CONSTRAINT CHECK_MINUTES CHECK("MINUTES" >= 0 AND "MINUTES" < 60)
);

CREATE TABLE ratpbot.DAYALERT (
  "ID" serial PRIMARY KEY,
  "ALERTID" INTEGER,
  "DAY" INTEGER,

  CONSTRAINT UNIQ_DAY_VALUES UNIQUE ("ALERTID", "DAY")
);

CREATE TABLE ratpbot.ALERTFORM (
  "ID" VARCHAR(255),
  "USERID" VARCHAR(255),
  "TRANSPORTTYPE" VARCHAR(255),
  "TRANSPORTCODE" VARCHAR(255),
  "TRANSPORTSTATION" VARCHAR(255),
  "ALERTTYPE" VARCHAR(255),
  "ALERTDAY" INTEGER,
  "HOUR" INTEGER,
  "MINUTES" INTEGER,

  PRIMARY KEY("ID", "USERID"),
  CONSTRAINT CHECK_HOUR_FORM CHECK("HOUR" >= 0 AND "HOUR" < 24),
  CONSTRAINT CHECK_MINUTES_FORM CHECK("MINUTES" >= 0 AND "MINUTES" < 60)
);

CREATE TABLE ratpbot.ALERTDAYFORM (
  "ID" VARCHAR(255),
  "DAY" INTEGER,

  PRIMARY KEY("ID", "DAY")
);

CREATE TABLE ratpbot.USERHOME (
  "USERID" VARCHAR(255) PRIMARY KEY,
  "TRAINTYPE" VARCHAR(255),
  "TRAINCODE" VARCHAR(255),
  "STATION" VARCHAR(255)
);

CREATE TABLE ratpbot.WELCOMEALERTHOUR (
  "USERID" VARCHAR(255) PRIMARY KEY,
  "HOUR" INTEGER,
  "MINUTE" INTEGER
);

ALTER TABLE ratpbot.DAYALERT ADD CONSTRAINT FK_DayAlert FOREIGN KEY ("ALERTID") REFERENCES ratpbot.ALERT("ID") ON DELETE CASCADE;