# --- !Ups

CREATE TABLE Traffic (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "TRANSPORT" VARCHAR(255),
  "LINE" VARCHAR(255),
  "SLUG" VARCHAR(255),
  "TITLE" VARCHAR(255),
  "MESSAGE" VARCHAR(255),
);

# --- !Downs
drop table Traffic;